services:
  "gitlab.justinelmore.dev": "gitlab:gitlab.justinelmore.dev"
  "forgejo.justinelmore.dev": "gitea:forgejo.justinelmore.dev"
  "git.justinelmore.dev": "gitea:git.justinelmore.dev"
gui:
  sidePanelWidth: 0.3 # gives more space to show side-by-side diff
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme Coldark-Dark -s
customCommands:
  - key: "F"
    command: "git fetch --prune"
    context: "localBranches"
    stream: true
os:
  openLink: open -n "$(echo {{link}} | sed 's/%2F/\//g')"
