services:
    "gitlab.justinelmore.dev": "gitlab:gitlab.justinelmore.dev"
gui:
    sidePanelWidth: 0.3 # gives more space to show side-by-side diff
git:
    paging:
        colorArg: always
        pager: delta --dark --paging=never --syntax-theme Coldark-Dark -s
customCommands:
    - key: "F"
      command: "git fetch --prune"
      context: "localBranches"
      stream: true
