gui:
  sidePanelWidth: 0.3 # gives you more space to show things side-by-side
git:  
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme Coldark-Dark -s

customCommands:
  - key: 'F'
    command: 'git fetch --prune'
    context: 'localBranches'
    stream: true
