scratchpad_space = 8
launch_timeout = 5

[[scratchpad]]
name = "discord"
target_type = "app"
target = "Discord"
position = [108, 67]
size = [1224, 765]
launch_type = "app"
launch_command = "Discord.app"

[[scratchpad]]
name = "finder"
target_type = "app"
target = "Finder"
position = [108, 67]
size = [1224, 765]
launch_type = "app"
launch_command = "Finder.app"

[[scratchpad]]
name = "notes"
target_type = "app"
target = "Notes"
position = [108, 67]
size = [1224, 765]
launch_type = "app"
launch_command = "Notes.app"

[[scratchpad]]
name = "beekeeper"
target_type = "app"
target = "Beekeeper Studio"
position = [108, 67]
size = [1224, 765]
launch_type = "app"
launch_command = "Beekeeper Studio.app"

[[scratchpad]]
name = "logseq"
target_type = "app"
target = "Logseq"
position = [108, 67]
size = [1224, 765]
launch_type = "app"
launch_command = "Logseq.app"

[[scratchpad]]
name = "wezterm"
target_type = "title"
target = "WezTermScratchPad"
position = [108, 67]
size = [1224, 765]
launch_type = "app_with_arg"
launch_command = [
    "WezTerm.app",
    "--config-file",
    "Users/justin/.config/wezterm/scratch.lua",
]
