scratchpad_space = 8
launch_timeout = 5

[[scratchpad]]
name = "discord"
target_type = "app"
target = "Google Chat"
position = [185, 108]
size = [2190, 1224]
launch_type = "app"
launch_command = "Google Chat.app"

[[scratchpad]]
name = "finder"
target_type = "app"
target = "Finder"
position = [185, 108]
size = [2190, 1224]
launch_type = "app"
launch_command = "Finder.app"

[[scratchpad]]
name = "notes"
target_type = "app"
target = "Notes"
position = [185, 108]
size = [2190, 1224]
launch_type = "app"
launch_command = "Notes.app"

[[scratchpad]]
name = "transmit"
target_type = "app"
target = "Transmit"
position = [185, 108]
size = [2190, 1224]
launch_type = "app"
launch_command = "Transmit.app"


[[scratchpad]]
name = "wezterm"
target_type = "title"
target = "WezTermScratchPad"
position = [185, 108]
size = [2190, 1224]
launch_type = "app_with_arg"
launch_command = [
    "WezTerm.app",
    "--config-file",
    "Users/jelmore/.config/wezterm/scratch.lua",
]
